#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Mon Aug 25 15:14:59 2025
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainFrame import MainFrame


class JsonViewerApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class JsonViewerApp

if __name__ == "__main__":
    app = JsonViewerApp(0)
    app.MainLoop()
